In [ ]:
import numpy as np

# creat one dimention array

In [ ]:
a=[1,2,3,4]
b=np.array(a)
b


# creat two dimention array

In [ ]:
c=[[1,2,3],[4,5,6],[7,8,9]]
d=np.array(c)
d

# creat three dimention array

In [2]:
import numpy as np
e=[[[1,2,3],[4,5,6],[7,8,9]]]
f=np.array(e)
f

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [ ]:
#how i check dimention and shape

In [ ]:
print("dimention is]",b.ndim)

In [ ]:
print("dimention is]",d.ndim)

In [ ]:
print("dimention is]",f.ndim)

# how i check shape of array

In [ ]:
print("total shape is=",b.shape)

In [ ]:
print("total shape is=",d.shape)

In [ ]:
print("total shape is=",f.shape)

# Q1 creat a user defined array ?

In [2]:
import numpy as np
a=([])
size=int(input("enter size:"))
for i in range(size):
    val=int(input("enter number:"))
    a.append(val)
print(a)
b=np.array(a)
b

enter size:2
enter number:1
enter number:2
[1, 2]


array([1, 2])

# pre defined functions

In [ ]:
#1.  zeros()==>all values will be creat with 0.
a=np.zeros(5)
a

In [ ]:
a=np.zeros((2,3))
a

In [ ]:
#2.  ones()==>all values will be creat with 1.

In [ ]:
a=np.ones(5)
a

In [ ]:
a=np.ones((3,4))
a

In [ ]:
#Eye()==>return digonal elements are 1 and rest all are zero.
a=np.eye(3,4)
a

In [ ]:
a=np.eye(5)
a

In [54]:
a = np.eye(2,4) 
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.]])

In [ ]:
a = np.eye(2) 
a

In [51]:
# diag() ==> 
a = np.diag((1,2))
a

array([[1, 0],
       [0, 2]])

In [ ]:
a.ndim

In [ ]:
a.shape

# randint

In [ ]:
#randint==>(min_value,max_value,total_random _number)


In [19]:
import numpy as np
a=np.random.randint(1,20,5)
a

array([18, 15, 12,  8,  4])

In [ ]:
#rand==>this function is used to generate random number between 0 to 1

In [39]:
a=np.random.rand(5)
a

array([0.3886372 , 0.16815221, 0.61247087, 0.01246669, 0.92559315])

In [ ]:
#randn==>this function is used to generate a random number between -3 to +3

In [38]:
a=np.random.randn(5)
a

array([-0.65172256,  0.73633477,  0.36147955, -1.12882705,  0.25525456])

# reshaping data

In [ ]:
a=np.random.randint(1,50,30)
a

In [ ]:
a.shape

In [ ]:
a.reshape(1,30)

In [ ]:
a.reshape(30,1)

In [ ]:
a.reshape(2,15)

In [ ]:
a.reshape(15,2)

In [ ]:
a.reshape(3,10)

In [ ]:
a.reshape(10,3)

In [ ]:
a=np.random.randint(1,60,20)
a

In [ ]:
a.shape

In [ ]:
a.reshape(2,10)

In [ ]:
a.reshape(10,2)

In [ ]:
a.reshape(5,4)

In [ ]:
a[1]

In [ ]:
a.reshape(4,5)

In [ ]:
a.reshape(20,1)

In [ ]:
a.reshape(1,20)

In [ ]:
# principal of -1=>row,column,total element==>
#row,total element=> column(-1)==>reshape
#column,total element==>row(-1)==>reshape

In [ ]:
a.shape

In [ ]:
a=a.reshape(-1,20)
a

In [ ]:
a=a.reshape(20,-1)
a

# seed function

In [ ]:
np.random.seed(11)
a=np.random.randint(1,50,10)
a

# view and copy

In [ ]:
a=np.array([10,20,30,40,50,60,70])
b=a[4:7]
b[:]=0
a

In [ ]:
p=np.array([10,20,30,40,50,60,70])
q=p[4:7].copy()
q[:]=0
p

In [ ]:
a=np.random.randint(2,4)
a

In [ ]:
a=[[1,2,3],[4,5,6],[7,8,9]]
b=np.array(c)
b

# conditional selection in numpy

In [6]:
import numpy as np


In [7]:
a=np.arange(1,16)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [8]:
a>10

array([False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True,  True])

In [9]:
a<10

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
       False, False, False, False, False, False])

In [10]:
b=a>10
a[b]


array([11, 12, 13, 14, 15])

In [11]:
c=a<10
a[c]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [61]:
a[a%2==0]
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

# operations on array

In [18]:
import numpy as np
a=np.arange(1,5)
a

array([1, 2, 3, 4])

In [19]:
a+3

array([4, 5, 6, 7])

In [20]:
a**3

array([ 1,  8, 27, 64], dtype=int32)

In [21]:
a**2

array([ 1,  4,  9, 16])

In [24]:
a=np.array([1,2,3,4]).reshape(2,2)
a

array([[1, 2],
       [3, 4]])

In [25]:
b=np.array([5,6,7,8]).reshape(2,2)
b

array([[5, 6],
       [7, 8]])

In [26]:
a+b #(1+5=6, 2+6=8, 3+7=10, 4+8=12)

array([[ 6,  8],
       [10, 12]])

In [27]:
a-b #(1-5=-4, 2-6=-4, 3-7=-4, 4-8=-4)

array([[-4, -4],
       [-4, -4]])

In [28]:
b/a #(5/1=5, 6/2=3, 7/3=2.33, 8/4=2)

array([[5.        , 3.        ],
       [2.33333333, 2.        ]])

In [29]:
a*b #(1*5=5, 2*6=12, 3*7=14,  4*8=32 )

array([[ 5, 12],
       [21, 32]])

In [30]:
a.dot(b)   #for matrix multiplication

array([[19, 22],
       [43, 50]])

In [31]:
a

array([[1, 2],
       [3, 4]])

In [32]:
b

array([[5, 6],
       [7, 8]])

# some more important numpy functions

In [33]:
a=np.array([10,20,30,40,50])
a

array([10, 20, 30, 40, 50])

In [34]:
np.min(a)

10

In [35]:
np.argmin(a)

0

In [36]:
np.max(a)

50

In [38]:
np.argmax(a)

4

In [39]:
np.sqrt(a)

array([3.16227766, 4.47213595, 5.47722558, 6.32455532, 7.07106781])

In [40]:
np.sin(a)

array([-0.54402111,  0.91294525, -0.98803162,  0.74511316, -0.26237485])

In [41]:
np.cos(a)

array([-0.83907153,  0.40808206,  0.15425145, -0.66693806,  0.96496603])

In [42]:
np.sort(a)

array([10, 20, 30, 40, 50])

# linspace

In [43]:
#linspace==>this function returens values between a given range with a same gape

In [46]:
a=np.linspace(1,2,5)
a

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [48]:
a=np.random.seed(10)
a=np.random.randint(1,21,9).reshape(3,3)
a


array([[10,  5, 16],
       [ 1, 18, 17],
       [18,  9, 10]])

In [50]:
np.sum(a)

104

In [51]:
np.sum(a,axis=1)#(16+11+13=40,17+13+16=46,3+16+11=30)

array([31, 36, 37])

In [52]:
np.sum(a,axis=0) #10+1+18

array([29, 32, 43])

In [53]:
np.cumsum(a)#10=5+16

array([ 10,  15,  31,  32,  50,  67,  85,  94, 104])

# np.unique(arr,return_index=True,return_counts=True)

In [54]:
#returns 1.original array
#2, index of perticular array
#3. frequncy of perticular original value

In [55]:
a=np.array([10,20,30,10,40,50,10])
np.unique(a, return_index=True, return_counts=True)

(array([10, 20, 30, 40, 50]),
 array([0, 1, 2, 4, 5], dtype=int64),
 array([3, 1, 1, 1, 1], dtype=int64))

# horizontal and vertical stacking

In [56]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
c=np.array([9,10,11,12])

In [57]:
a

array([1, 2, 3, 4])

In [58]:
b

array([5, 6, 7, 8])

In [59]:
c

array([ 9, 10, 11, 12])

In [60]:
np.hstack((a,b,c))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [63]:
np.vstack((a,b,c))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [13]:
#Q1==>write statement to import numpy?
# Q2==>create an array which contains value 8, 15 times?
# q3==> create an array of 20 random integers?
# Q4==>create a one dimentional   array and convert that into 3*3 matrix?
# Q5==>concatenate 2D array of size 3*3?
# but all the values should be between -3 to +3?
# Q6==>create an array of elements from 40 to 55?
# Q7==>create an 3*4 array which contains digonal elements as 1?
#Q8==>how are numpy arrays better than a python's list?
#Q9==>

In [14]:
#Q1==>write statement to import numpy?
import numpy as np

In [18]:
#Q2==>create an array which contains value 8, 15 times?
a=np.full((5,3),8)
a

array([[8, 8, 8],
       [8, 8, 8],
       [8, 8, 8],
       [8, 8, 8],
       [8, 8, 8]])

In [24]:
# q3==> create an array of 20 random integers?
a=np.random.randint(1,20,20)
a

array([ 7, 18, 13, 13,  8, 16,  7, 19,  4,  1,  6, 11, 11, 14,  5, 14,  3,
        4, 14, 15])

In [32]:
# Q4==>create a one dimentional   array and convert that into 3*3 matrix?
a=np.array(([1,2,3,4,5,6,7,8,9])).reshape(3,3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
# Q5==>concatenate 2D array of size 3*3? but all the values should be between -3 to +3?
import numpy as np
a=np.array([[1,2,3,4],[9,10,11,12]])
b=np.array([[5,6,7,8]])
c=np.concatenate((a,b))
c


array([[ 1,  2,  3,  4],
       [ 9, 10, 11, 12],
       [ 5,  6,  7,  8]])

In [49]:
# Q6==>create an array of elements from 40 to 55?
a=np.arange(40,56)
a

array([40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55])

In [55]:
# Q7==>create an 3*4 array which contains digonal elements as 1?
a=np.eye(3,4)
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [ ]:
#Q8==>how are numpy arrays better than a python's list?
#Ans==>
# ==> fewer code
# ==> sort index
# ==> same data type